---
title: "Sewanee Soccer"
author: "Nora Stanley"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns

---
# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(flexdashboard)

data<-read_excel("C:/Users/norab/repos/sewanee_soccer/data/app_data.xlsx")
data<-data%>%
  rename(Timestamp=`46131.461354166669`)

data<-data%>%
  rename(Type=fwrd_pass,
         Status=complete,
         third='attacking third')

pass_third_data<-data%>%
  filter(Type %in% c("fwrd_pass","bck_pass"))%>%
  group_by(third, Type)%>%
  summarise(count=n(), .groups="drop")

pass_third_data$third<- factor(pass_third_data$third, levels=c('attacking third','middle third','defensive third'))
pass_third_data$Type<- factor(pass_third_data$Type, levels=c('fwrd_pass','bck_pass'))
```

# Attack
## Top Left
```{r, echo=FALSE}
# put in different r chunk
ggplot(pass_third_data, aes(
  x=third,
  y=count,
  fill=Type))+
  geom_col(stat="identity",position="dodge")+
  labs(
    title="Tactical Approach in Each Third",
    subtitle="Number of Passes in Each Third",
    x="Third of the Field",
    y="Number of Passes",
    fill="Type of Pass"
  )+
  scale_fill_manual(
    values=c("fwrd_pass"='red',"bck_pass"='black') #change, too harsh
  ) #theme; gg_themes???

```

## Top Right
```{r, echo=FALSE}
pass_dribble_data<-data%>%
  filter(Type %in% c("fwrd_pass","bck_pass","dribble"))%>%
  mutate(Status = gsub('successful','complete', Status))
pass_dribble_data<-pass_dribble_data%>%
  mutate(Status = gsub('uncomplete','incomplete',Status))

pass_dribble_data<-pass_dribble_data%>%
  mutate(
    completion=case_when(
      Status %in% c("complete") ~ 1,
      Status %in% c("incomplete") ~ 0),
    action=case_when(
      Type %in% c("fwrd_pass", "bck_pass") ~ "pass",
      Type == "dribble" ~ "dribble"
    )
  )

pass_dribble_rate<-pass_dribble_data%>%
  group_by(third, action)%>%
  summarise(completion_rate = mean(completion), .groups="drop")

pass_dribble_rate<-pass_dribble_rate%>%
  mutate(third = factor(third, levels = c("attacking third","middle third","defensive third")))%>%
  mutate(action = factor(action, levels = c("pass","dribble")))

ggplot(pass_dribble_rate, aes(
  x=third,
  y=completion_rate,
  fill=action
  ))+
  geom_col(stat="identity", position=position_dodge(preserve="single"))+
  labs(
    title="Success in Each Third",
    subtitle="Pass and Dribble Competion by Third",
    caption="There were no dribbles attempted in the defensive third",
    x="Third of the Field",
    y="Completion Rate",
    color="Action"
  )+
  scale_fill_manual(
    values= c("pass"='yellow',"dribble"= 'turquoise')
  )
```
## Bottom
```{r}
ground_air_data<-pass_dribble_data%>%
  filter(Type == 'fwrd_pass')%>%
  group_by(third, ground)%>%
  summarise(count = n(), .groups="drop")%>%
  mutate(third = factor(third, levels = c('attacking third','middle third', 'defensive third')),
         ground = factor(ground, levels = c('ground','air')))

ggplot(ground_air_data, aes(
  x=third,
  y=count,
  fill=ground
))+
  geom_col(stat="identity", position=position_dodge(preserve="single"))+
  labs(
    title="Altitude of Attack",
    subtitle="Pass Attempts on the Ground or in the Air by Third",
    caption="No Pass Attempts in the Air in the Defensive Third",
    x="Third of the Field",
    y="Number of Pass Attempts",
    color="Type of Pass"
  )

```



# Defense
## Top Left
```{r, echo=FALSE}
defense_data<-read_excel("C:/Users/norab/repos/sewanee_soccer/defense_data/defense_data.xlsx")
defense_data<-defense_data%>%
  rename(timestamp=`46134.173657407409`,
         action=pass_allowed,
         success=complete,
         third='attacking third')
pass_defense<-defense_data%>%
  group_by(action,success, third)%>%
  summarise(count = n(), .groups="drop")
pass_defense_filter<-pass_defense%>%
  filter(action == 'pass_allowed',
         success %in% c('complete','incomplete'))
pass_defense_filter$third<- factor(pass_defense_filter$third, levels = c('attacking third','middle third', 'defensive third'))

ggplot(pass_defense_filter, aes(
  x=third,
  y=count,
  fill=success
))+
  geom_col(stat="identity", position="dodge")+
  scale_fill_manual(
    values = c(complete='red',incomplete='green')
  )+
  labs(
    title="Tactics Against Passing",
    subtitle="Number of Passes for the Opposition",
    x="Third of the Field",
    y="Number of Passes",
    fill="Key"
  )+
  theme_light()
```

## Top Right
```{r, echo=FALSE}

tackle_data<-defense_data%>%
  filter(action == 'tackle')
tackle_count_data<-tackle_data%>%
  group_by(success, third)%>%
  summarise(count = n(), .groups="drop")%>%
  mutate(third = factor(third, levels = c('attacking third','middle third','defensive third')),
         success = factor(success, levels = c('won','not won')))

ggplot(tackle_count_data, aes(
  x=third,
  y=count,
  fill=success
))+
  geom_col(stat="identity", position=position_dodge(preserve="single"))+
  scale_fill_manual(
    values = c(won='green','not won'='red')
  )+
  labs(
    title="Defensive Success on the Ground",
    subtitle="Number of Tackles Won by Third",
    x="Third of the Field",
    y="Number of Tackles",
    fill="Key",
    caption="No Tackles Not Won in the Attacking and Defensive Thirds"
  )

```

##Bottom Left
```{r, echo=FALSE}

header_data<-defense_data%>%
  filter(action == 'header',
         third != 'attacking third')
header_data_filter<-header_data%>%
  mutate(third = factor(third, levels = c('middle third','defensive third')),
         success = factor(success, levels = c('won','not won')))
header_count_data<-header_data_filter%>%
  group_by(success, third)%>%
  summarise(count = n(), .groups="drop")

ggplot(header_count_data, aes(
  x=third,
  y=count,
  fill=success
))+
  geom_col(stat="identity",position="dodge")+
  scale_fill_manual(
    values = c(won='green','not won'='red')
  )+
  scale_y_continuous(limits = c(0,4))+
  labs(
    title="Defensive Success in the Air",
    subtitle="Number of Headers Won by Third",
    x="Third of the Field",
    y="Number of Headers",
    fill="Key",
    caption="No Headers in the Attacking Third"
  )
```

# Comparison

# Conclusion
